logging:
  level:
    org.springdoc: INFO

spring:
  application:
    name: tfi
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/tfi
    username: tfi
    password: tfi
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

  mail:
    host: localhost         # MailHog
    port: 1025              # MailHog SMTP
    username: ""            # sin auth
    password: ""            # sin auth
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
    default-encoding: UTF-8
    test-connection: false

springdoc:
  override-with-generic-response: false

server:
  port: 8080

# —— Mercado Pago ——————————————————————————————————————
mp:
  api:
    public-key: TEST-57f55bd7-4769-45fe-8268-c776df0b3791
    access-token: TEST-4873687935529088-103120-fe51dfbb79ff5e60c5cb340551bd4715-806147879
  sena-percent: 0.30

# —— Base URL para integraciones (HU11 webhook) —————————
app:
  base-url: ${APP_PUBLIC_BASE_URL:https://predependent-cindy-inbond.ngrok-free.dev
  public-base-url: ${APP_PUBLIC_BASE_URL:https://predependent-cindy-inbond.ngrok-free.dev

